---
sidebar: sidebar 
permalink: faq-cloud-compliance.html 
keywords: faq, frequently asked questions, questions, cloud compliance, data sense 
summary: 質問に対する簡単な回答を探している場合は、この FAQ が役立ちます。 
---
= NetApp Data Classificationに関するよくある質問
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
質問に対する簡単な回答を探している場合は、この FAQ が役立ちます。



== NetApp Data Classification

次の質問は、データ分類に関する一般的な理解を提供します。



=== データ分類はどのように機能しますか?

データ分類は、NetApp Consoleシステムおよびストレージ システムとともに AI の別のレイヤーを展開します。次に、ボリューム、バケット、データベース、その他のストレージ アカウント上のデータをスキャンし、見つかったデータの分析情報をインデックス化します。データ分類では、正規表現とパターン マッチングを中心に構築される一般的な代替ソリューションとは対照的に、人工知能と自然言語処理の両方を活用します。

データ分類では AI を使用してデータのコンテキストを理解し、正確な検出と分類を実現します。最新のデータ タイプとスケールに合わせて設計されているため、AI によって駆動されます。また、強力で正確な検出と分類を提供するために、データのコンテキストも理解します。

link:concept-classification.html["データ分類の仕組みについて詳しく見る"] 。



=== データ分類には REST API がありますか? また、サードパーティのツールと連携できますか?

はい、データ分類には、コンソール コア プラットフォームの一部であるデータ分類バージョンでサポートされている機能用の REST API があります。見るlink:api-classification.html["APIのドキュメント"] 。



=== データ分類はクラウド マーケットプレイスを通じて利用できますか?

データ分類はNetApp Consoleのコア機能の一部であるため、このサービスにマーケットプレイスを使用する必要はありません。



== データ分類のスキャンと分析

次の質問は、データ分類のスキャン パフォーマンスと分析に関するものです。



=== データ分類はどのくらいの頻度でデータをスキャンしますか?

データの最初のスキャンには多少時間がかかりますが、後続のスキャンでは増分変更のみが検査されるため、システムスキャン時間が短縮されます。データ分類では、一度に 6 つのリポジトリをラウンドロビン方式で継続的にスキャンするため、変更されたすべてのデータが非常に迅速に分類されます。

link:task-scanning-overview.html["スキャンの仕組みを学ぶ"] 。

データ分類では、データベースは 1 日に 1 回だけスキャンされます。データベースは他のデータ ソースのように継続的にスキャンされるわけではありません。

データ スキャンは、ストレージ システムとデータにほとんど影響を与えません。



=== スキャンのパフォーマンスは変化しますか?

スキャンのパフォーマンスは、ネットワーク帯域幅と環境内の平均ファイル サイズによって異なります。また、ホスト システム (クラウドまたはオンプレミス) のサイズ特性によっても異なります。。 link:concept-classification.html["データ分類インスタンス"]そしてlink:task-deploy-overview.html["データ分類の導入"]詳細についてはこちらをご覧ください。

新しいデータ ソースを最初に追加するときに、完全な「分類」(マップと分類) スキャンではなく、「マッピング」(マッピングのみ) スキャンのみを実行するように選択することもできます。ファイルにアクセスして内部のデータを確認する必要がないため、データ ソースのマッピングを非常に迅速に実行できます。link:task-scanning-overview.html["マッピングスキャンと分類スキャンの違いを確認する"] 。



=== データ分類を使用してデータを検索できますか?

データ分類には広範な検索機能が用意されており、接続されているすべてのソースから特定のファイルやデータを簡単に検索できます。データ分類により、ユーザーはメタデータが反映するものよりもさらに深く検索できるようになります。これは言語に依存しないサービスであり、ファイルを読み取って、名前や ID などの多数の機密データ タイプを分析することもできます。たとえば、ユーザーは構造化データ ストアと非構造化データ ストアの両方を検索して、企業ポリシーに違反してデータベースからユーザー ファイルに漏洩した可能性のあるデータを見つけることができます。検索は後で使用するために保存することができ、設定された頻度で検索して結果に対してアクションを実行するためのポリシーを作成することもできます。

関心のあるファイルが見つかったら、タグ、システム アカウント、バケット、ファイル パス、カテゴリ (分類から)、ファイル サイズ、最終更新日時、アクセス許可の状態、重複、機密レベル、個人データ、ファイル内の機密データの種類、所有者、ファイルの種類、ファイル サイズ、作成時刻、ファイル ハッシュ、データが注意を求める誰かに割り当てられたかどうかなどの特性を一覧表示できます。フィルターを適用して、関係のない特性を除外することができます。

データ分類には、適切な権限がある場合にファイルを移動または削除できるようにするロールベースのアクセス制御 (RBAC) も備わっています。適切な権限がない場合、タスクは組織内で適切な権限を持つユーザーに割り当てることができます。



== データ分類管理とプライバシー

次の質問は、データ分類とプライバシー設定を管理する方法に関する情報を提供します。



=== データ分類を有効または無効にするにはどうすればよいですか?

まず、コンソールまたはオンプレミス システムにデータ分類のインスタンスをデプロイする必要があります。インスタンスが実行されると、[構成] タブまたは特定のシステムを選択して、既存のシステム、データベース、およびその他のデータ ソースでサービスを有効にできます。link:task-getting-started-compliance.html["始める方法を学ぶ"] 。


NOTE: データ ソースでデータ分類をアクティブ化すると、すぐに初期スキャンが実行されます。スキャン結果はすぐに表示されます。

データ分類構成ページから、データ分類による個々のシステム、データベース、またはファイル共有グループのスキャンを無効にすることができます。見るlink:task-managing-compliance.html["データ分類からデータソースを削除する"] 。

データ分類インスタンスを完全に削除するには、クラウド プロバイダーのポータルまたはオンプレミスの場所からデータ分類インスタンスを手動で削除します。



=== サービスは特定のディレクトリ内のデータのスキャンを除外できますか?

○データ分類で特定のデータ ソース ディレクトリにあるスキャン データを除外する場合は、そのリストを分類エンジンに提供できます。変更を適用すると、データ分類では指定されたディレクトリ内のスキャン データが除外されます。link:task-exclude-scan-paths.html["詳細情報"] 。



=== ONTAPボリューム上に存在するスナップショットはスキャンされますか?

いいえ。データ分類では、コンテンツがボリューム内のコンテンツと同一であるため、スナップショットはスキャンされません。



=== ONTAPボリュームでデータ階層化を有効にするとどうなりますか?

データ分類がマッピングのみのスキャンを使用してオブジェクト ストレージに階層化されたコールド データを持つボリュームをスキャンする場合、ローカル ディスク上のデータとオブジェクト ストレージに階層化されたコールド データを含むすべてのデータがスキャンされます。これは、階層化を実装するNetApp以外の製品にも当てはまります。

マッピングのみのスキャンでは、コールド データはヒートアップされず、コールドのままオブジェクト ストレージに残ります。一方、マップと分類スキャンを実行する場合、構成によってはコールド データがヒートアップする可能性があります。



== ソースシステムの種類とデータ型

次の質問は、スキャンできるストレージの種類と、スキャンされるデータの種類に関するものです。



=== 政府地域に展開する場合、何か制限はありますか?

データ分類は、コンソール エージェントが政府リージョン (AWS GovCloud、Azure Gov、または Azure DoD) にデプロイされている場合にサポートされます (「制限モード」とも呼ばれます)。



=== インターネットにアクセスできないサイトにデータ分類をインストールする場合、どのデータ ソースをスキャンできますか?


IMPORTANT: BlueXPプライベート モード (レガシーBlueXPインターフェイス) は通常、インターネット接続がなく、AWS Secret Cloud、AWS Top Secret Cloud、Azure IL6 などの安全なクラウド領域があるオンプレミス環境で使用されます。NetApp は、従来のBlueXPインターフェースを使用してこれらの環境を引き続きサポートします。従来のBlueXPインターフェースのプライベートモードのドキュメントについては、link:https://docs.netapp.com/us-en/console-setup-admin/media/BlueXP-Private-Mode-legacy-interface.pdf["BlueXPプライベートモードの PDF ドキュメント"^] 。

データ分類では、オンプレミス サイトのローカルにあるデータ ソースからのデータのみをスキャンできます。現時点では、データ分類では、次のローカル データ ソースを「プライベート モード」(「ダーク」サイトとも呼ばれます) でスキャンできます。

* オンプレミスのONTAPシステム
* データベーススキーマ
* Simple Storage Service (S3) プロトコルを使用するオブジェクト ストレージ




=== どのようなファイル形式がサポートされていますか?

データ分類では、すべてのファイルをスキャンしてカテゴリとメタデータの分析情報を取得し、ダッシュボードのファイル タイプ セクションにすべてのファイル タイプを表示します。

データ分類が個人識別情報 (PII) を検出する場合、または DSAR 検索を実行する場合は、次のファイル形式のみがサポートされます。

`+.CSV, .DCM, .DOC, .DOCX, .JSON, .PDF, .PPTX, .RTF, .TXT, .XLS, .XLSX, Docs, Sheets, and Slides+`



=== データ分類ではどのような種類のデータとメタデータをキャプチャしますか?

データ分類を使用すると、データ ソースに対して一般的な「マッピング」スキャンまたは完全な「分類」スキャンを実行できます。マッピングではデータの概要のみが提供されますが、分類ではデータの詳細なスキャンが提供されます。ファイルにアクセスして内部のデータを確認する必要がないため、データ ソースのマッピングを非常に迅速に実行できます。

* *データ マッピング スキャン (マッピングのみのスキャン)*: データ分類ではメタデータのみをスキャンします。これは、全体的なデータ管理とガバナンス、プロジェクトの迅速なスコープ設定、非常に大規模な資産、優先順位付けに役立ちます。データ マッピングはメタデータに基づいており、高速スキャンと見なされます。
+
高速スキャンの後、データ マッピング レポートを生成できます。このレポートは、企業のデータ ソースに保存されているデータの概要であり、リソースの使用率、移行、バックアップ、セキュリティ、コンプライアンス プロセスに関する意思決定に役立ちます。

* *データ分類ディープ スキャン (マップと分類スキャン)*: データ分類では、環境全体で標準プロトコルと読み取り専用権限を使用してデータをスキャンします。選択されたファイルが開かれ、ビジネス関連の機密データ、個人情報、およびランサムウェアに関連する問題がないかスキャンされます。
+
完全スキャン後には、データ調査ページでのデータの表示と絞り込み、ファイル内の名前の検索、ソース ファイルのコピー、移動、削除など、データに適用できる追加のデータ分類機能が多数あります。



データ分類では、ファイル名、権限、作成時間、最終アクセス、最終変更などのメタデータを取得します。これには、データ調査の詳細ページとデータ調査レポートに表示されるすべてのメタデータが含まれます。

データ分類では、個人情報 (PII) や機密個人情報 (SPII) など、さまざまな種類のプライベート データを識別できます。個人データの詳細については、xref:reference-private-data-categories.html[データ分類がスキャンする個人データのカテゴリ] 。



=== データ分類情報を特定のユーザーに制限できますか?

はい、データ分類はNetApp Consoleと完全に統合されています。  NetApp Consoleユーザーは、権限に応じて表示資格のあるシステムの情報のみを表示できます。

さらに、特定のユーザーにデータ分類設定の管理権限を与えずにデータ分類スキャン結果の表示のみを許可する場合は、そのユーザーに *分類閲覧者* ロール ( NetApp Consoleを標準モードで使用する場合) または *コンプライアンス閲覧者* ロール ( NetApp Consoleを制限モードで使用する場合) を割り当てることができます。link:concept-classification.html["詳細情報"] 。



=== ブラウザとデータ分類の間で送信されるプライベートデータに誰でもアクセスできますか?

いいえ。ブラウザとデータ分類インスタンス間で送信されるプライベート データは、TLS 1.2 を使用したエンドツーエンドの暗号化によって保護されるため、 NetAppおよびNetApp以外の関係者はそれを読み取ることができません。データ分類は、アクセスを要求して承認しない限り、データや結果をNetAppと共有しません。

スキャンされたデータは環境内に残ります。



=== 機密データはどのように扱われますか?

NetApp は機密データにアクセスできず、UI に表示しません。機密データはマスクされます。たとえば、クレジットカード情報の場合は最後の 4 桁が表示されます。



=== データはどこに保存されますか?

スキャン結果は、データ分類インスタンス内の Elasticsearch に保存されます。



=== データにはどのようにアクセスしますか?

データ分類は、API 呼び出しを通じて Elasticsearch に保存されているデータにアクセスします。このアクセスには認証が必要であり、AES-128 を使用して暗号化されます。  Elasticsearch に直接アクセスするには、ルート アクセスが必要です。



== ライセンスとコスト

次の質問は、データ分類を使用するためのライセンスとコストに関するものです。



=== データ分類にはどれくらいの費用がかかりますか?

データ分類は、 NetApp Consoleのコア機能です。料金はかかりません。



== コンソールエージェントの展開

次の質問はコンソール エージェントに関するものです。



=== コンソールエージェントとは何ですか?

コンソール エージェントは、クラウド アカウント内またはオンプレミスのコンピューティング インスタンスで実行されるソフトウェアであり、 NetApp Consoleがクラウド リソースを安全に管理できるようにします。データ分類を使用するには、コンソール エージェントを展開する必要があります。



=== コンソール エージェントはどこにインストールする必要がありますか?

データをスキャンする場合、 NetApp Consoleエージェントを次の場所にインストールする必要があります。

* AWS のCloud Volumes ONTAPまたはAmazon FSx for ONTAPの場合: コンソールエージェントは AWS にあります。
* Azure またはAzure NetApp FilesのCloud Volumes ONTAPの場合: コンソール エージェントは Azure にあります。
* GCP のCloud Volumes ONTAPの場合: コンソール エージェントは GCP にあります。
* オンプレミスのONTAPシステムの場合: コンソール エージェントはオンプレミスです。


これらの場所にデータがある場合は、 https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html#when-to-use-multiple-connectors["複数のコンソールエージェント"^] 。



=== データ分類には資格情報へのアクセスが必要ですか?

データ分類自体はストレージ資格情報を取得しません。代わりに、コンソール エージェント内に保存されます。

データ分類では、スキャン前に共有をマウントするための CIFS 資格情報などのデータ プレーン資格情報を使用します。



=== サービスとコンソール エージェント間の通信には HTTP が使用されますか?

はい、データ分類は HTTP を使用してコンソール エージェントと通信します。



== データ分類の展開

次の質問は、個別のデータ分類インスタンスに関連しています。



=== データ分類はどのような展開モデルをサポートしていますか?

NetApp Consoleを使用すると、オンプレミス、クラウド、ハイブリッド環境など、事実上あらゆる場所のシステムをスキャンしてレポートできます。データ分類は通常、SaaS モデルを使用して展開されます。このモデルでは、サービスはコンソール インターフェイスを介して有効化され、ハードウェアやソフトウェアのインストールは必要ありません。このクリックアンド実行の展開モードでも、データ ストアがオンプレミスにあるかパブリック クラウドにあるかに関係なく、データ管理を行うことができます。



=== データ分類にはどのようなタイプのインスタンスまたは VM が必要ですか?

いつlink:task-deploy-cloud-compliance.html["クラウドに展開"]:

* AWS では、データ分類は 500 GiB GP2 ディスクを備えた m6i.4xlarge インスタンスで実行されます。デプロイ時により小さいインスタンス タイプを選択できます。
* Azure では、データ分類は 500 GiB のディスクを備えた Standard_D16s_v3 VM 上で実行されます。
* GCP では、データ分類は 500 GiB の標準永続ディスクを備えた n2-standard-16 VM 上で実行されます。


link:concept-classification.html["データ分類の仕組みについて詳しく見る"] 。



=== データ分類を自分のホストに展開できますか?

○ネットワークまたはクラウドでインターネットにアクセスできる Linux ホストにデータ分類ソフトウェアをインストールできます。すべてが同じように機能し、コンソールを通じてスキャン構成と結果を引き続き管理できます。見るlink:task-deploy-compliance-onprem.html["オンプレミスでのデータ分類の導入"]システム要件とインストールの詳細については、こちらをご覧ください。



=== インターネットにアクセスできない安全なサイトはどうなりますか?

はい、それもサポートされています。あなたはできるlink:task-deploy-compliance-dark-site.html["インターネットにアクセスできないオンプレミスサイトにデータ分類を展開する"]完全に安全なサイトのために。
