---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, data sense, classification, scan shares 
summary: 既知の制限事項では、このリリースの製品ではサポートされていない機能、または正しく相互運用されない機能が特定されます。これらの制限事項をよく確認してください。 
---
= NetApp Data Classificationの既知の制限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
既知の制限事項では、このリリースではサポートされていない機能や正しく相互運用されない機能が特定されます。これらの制限事項をよく確認してください。



== NetApp Data Classification の無効化オプション

2023 年 12 月 (バージョン 1.26.6) リリースでは、次のオプションが削除されました。

* 監査ログ収集を有効にするオプションが無効になっています。
* ディレクトリ調査中は、ディレクトリ別に個人識別情報 (PII) データの数を計算するオプションは使用できません。
* Azure Information Protection (AIP) ラベルを使用してデータを統合するオプションが無効になりました。




== データ分類スキャン

データ分類スキャンでは次の制限が発生します。



=== データ分類はボリューム内の1つの共有のみをスキャンします

1 つのボリュームの下に複数のファイル共有がある場合、データ分類は最上位階層の共有をスキャンします。たとえば、次のような共有があるとします。

* /A
* /A/B
* /C
* /D/E


この構成では、/A のデータのみがスキャンされます。  /C および /D 内のデータはスキャンされません。

.回避策
ボリューム内のすべての共有からデータをスキャンしていることを確認するための回避策があります。次の手順を実行します。

. システムに、スキャンするボリュームを追加します。
. データ分類がボリュームのスキャンを完了したら、[データ調査] ページに移動し、スキャンされている共有を確認するためのフィルターを作成します。
+
「システム名」と「ディレクトリ タイプ = 共有」でデータをフィルターし、スキャンされている共有を確認します。

. ボリューム内に存在する共有の完全なリストを取得して、スキャンされていない共有を確認できます。
. link:task-scanning-file-shares.html["残りの共有を共有グループに追加する"] 。
+
すべての共有を個別に追加します。例:

+
....
/C
/D
....
. 複数の共有があるシステム内の各ボリュームに対して、これらの手順を実行します。




=== 最終アクセスタイムスタンプ

データ分類がディレクトリのスキャンを実行すると、そのスキャンはディレクトリの **最終アクセス** フィールドに影響します。  **最終アクセス** フィールドを表示すると、そのメタデータにはスキャンの日時またはユーザーがディレクトリに最後にアクセスした時刻が反映されます。
