---
sidebar: sidebar 
permalink: task-active-directory.html 
keywords: active directory, ad, data sense, cloud data sense 
summary: グローバル Active Directory をNetApp Data Classificationと統合して、ファイル所有者やファイルにアクセスできるユーザーとグループに関する Data Classification のレポート結果を強化できます。 
---
= Active DirectoryをNetApp Data Classificationと統合する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
グローバル Active Directory をNetApp Data Classificationと統合して、ファイル所有者やファイルにアクセスできるユーザーとグループに関する Data Classification のレポート結果を強化できます。

特定のデータ ソース (以下にリスト) を設定する場合、データ分類で CIFS ボリュームをスキャンするには、Active Directory の資格情報を入力する必要があります。この統合により、データ分類では、それらのデータ ソースに存在するデータのファイル所有者と権限の詳細が提供されます。これらのデータ ソースに入力された Active Directory は、ここで入力するグローバル Active Directory 資格情報とは異なる場合があります。データ分類では、統合されたすべての Active Directory でユーザーと権限の詳細を検索します。

この統合により、データ分類の次の場所に追加情報が提供されます。

* 「ファイル所有者」を使用することができますlink:task-investigate-data.html["フィルター"]調査ペインのファイルのメタデータで結果を確認します。  SID (セキュリティ ID) を含むファイル所有者の代わりに、実際のユーザー名が入力されます。
+
また、ファイル所有者の詳細情報（アカウント名、メール アドレス、SAM アカウント名）を表示したり、そのユーザーが所有するアイテムを表示したりすることもできます。

* 「すべてのアクセス許可を表示」ボタンを選択すると、各ファイルとディレクトリのlink:task-investigate-data.html["完全なファイル権限"]を確認できます。
* の中でlink:task-controlling-governance-data.html["ガバナンスダッシュボード"]、Open Permissions パネルにデータに関するより詳細な情報が表示されます。



NOTE: ローカル ユーザーの SID および不明なドメインの SID は、実際のユーザー名に変換されません。



== サポートされているデータソース

Active Directory とデータ分類の統合により、次のデータ ソース内のデータを識別できます。

* Azure NetApp Files
* Cloud Volumes ONTAP
* ONTAP向け FSx
* オンプレミスのONTAPシステム




== Active Directoryサーバーに接続する

データ分類を展開し、データ ソースのスキャンを有効にしたら、データ分類を Active Directory と統合できます。  Active Directory には、DNS サーバー IP アドレスまたは LDAP サーバー IP アドレスを使用してアクセスできます。

Active Directory の資格情報は読み取り専用にすることができますが、管理者の資格情報を提供することで、データ分類は昇格された権限を必要とするすべてのデータを読み取ることができるようになります。資格情報は、データ分類インスタンスに保存されます。

CIFSボリューム/ファイル共有の場合、NetApp Data Classificationスキャンによってファイルの「最終アクセス時刻」が変更されないようにするには、ユーザーに属性書き込み権限が必要です。可能であれば、Active Directoryで設定したユーザーを、組織内のすべてのファイルへのアクセス権限を持つ親グループに所属させることをお勧めします。

.要件
* 社内のユーザー用に Active Directory がすでに設定されている必要があります。
* Active Directory の情報が必要です:
+
** DNSサーバーのIPアドレス、または複数のIPアドレス
+
または

+
LDAPサーバーのIPアドレス、または複数のIPアドレス

** サーバーにアクセスするためのユーザー名とパスワード
** ドメイン名（アクティブディレクトリ名）
** セキュアLDAP（LDAPS）を使用しているかどうか
** LDAP サーバー ポート (通常、LDAP の場合は 389、セキュア LDAP の場合は 636)


* データ分類インスタンスによる送信通信のために、次のポートが開いている必要があります。
+
[cols="20,20,30,30"]
|===
| プロトコル | ポート | デスティネーション | 目的 


| TCPとUDP | 389 | Active Directory | LDAP 


| TCP | 636 | Active Directory | LDAP over SSL 


| TCP | 3268 | Active Directory | グローバルカタログ 


| TCP | 3269 | Active Directory | SSL経由のグローバルカタログ 
|===


.手順
. データ分類で、**構成** を選択します。
. **設定**タブに切り替えます。
. Active Directory の見出しで、**追加**を選択します。
. Active Directoryへの接続ダイアログで、Active Directoryの詳細を入力し、*接続*を選択します。
+
必要に応じて、「*IP を追加*」を選択して複数の IP アドレスを追加できます。

+
データ分類は Active Directory に統合され、構成ページに新しいセクションが追加されます。





== Active Directory統合を管理する

Active Directory統合で値を変更する必要がある場合は、Data ClassificationでActive Directory設定を更新する必要があります。Data Classificationの**Configuration**メニューに戻り、設定タブに切り替えて変更を行ってください。

Active Directory の下にある **削除** ボタンを選択することで、統合を削除することもできます。
