---
sidebar: sidebar 
permalink: task-scanning-overview.html 
keywords: cloud compliance, get started, enable cloud compliance, cifs credentials, smb credentials, cloud compliance access, privacy, compliance, dp volumes, data protection volumes, CVO, Cloud Volumes ONTAP, data sense, cloud data sense, map-only scans, map and classify, full 
summary: NetApp Data Classificationを使用してデータ ソースをスキャンします。 
---
= NetApp Data Classificationでデータソースをスキャン
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Data Classificationは、選択したリポジトリ（ボリューム、データベーススキーマ、またはその他のユーザーデータ）内のデータをスキャンし、個人情報や機密データを特定します。Data Classificationはその後、組織のデータをマッピングし、各ファイルを分類し、データ内のあらかじめ定義されたパターンを識別します。スキャンの結果として、個人情報、機微な個人情報、データカテゴリ、ファイルタイプのインデックスが作成されます。

最初のスキャンの後、データ分類はラウンドロビン方式でデータを継続的にスキャンし、増分変更を検出します。そのため、インスタンスを実行し続けることが重要です。

ボリューム レベルまたはデータベース スキーマ レベルでスキャンを有効または無効にすることができます。



== スキャンタイプを理解する

データ分類では、次の 2 種類のスキャンを実行できます。

* **マップのみのスキャン**では、データの概要のみが提供され、選択されたデータソースに対して実行されます。マップのみのスキャンは、ファイルにアクセスして内部のデータを確認しないため、フルスキャンよりも時間がかかりません。
* **フルスキャン**は、データの詳細なスキャンを提供します。フルスキャンには、マッピングスキャンとファイル内のデータの分類が含まれます。



TIP: マップのみのスキャンを実行すると、データの概要を把握し、フルスキャンを実行する特定の領域を特定するのに役立ちます。

表を確認して、マップのみのスキャンとフルスキャンでどのような情報が表示されるかを確認してください。

[cols="47,18,18"]
|===
| 特徴 | フルスキャン | マップのみのスキャン 


| スキャン速度 | 遅い | 速い 


| 料金 | 空き | 空き 


| 容量 | 500 TiB に制限されます* | 500 TiB に制限されます* 


| ファイルの種類と使用容量の一覧 | はい | はい 


| ファイル数と使用容量 | はい | はい 


| ファイルの古さとサイズ | はい | はい 


| 実行する能力link:task-controlling-governance-data.html["データマッピングレポート"] | はい | はい 


| ファイルの詳細を表示するためのデータ調査ページ | はい | いいえ 


| ファイル内の名前を検索する | はい | いいえ 


| 作成するlink:task-using-policies.html["保存されたクエリ"]カスタム検索結果を提供する | はい | いいえ 


| 他のレポートを実行する機能 | はい | いいえ 


| ファイルのメタデータを表示する機能** | はい | はい 
|===
{asterisk}Data Classificationは、スキャンするデータ量に制限を設けません。各Consoleエージェントは、500 TiBまでのデータのスキャンと表示をサポートします。500 TiBを超えるデータをスキャンするには、link:https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html#connector-installation["別のコンソールエージェントをインストールする"^]次にlink:task-deploy-overview.html["別のデータ分類インスタンスをデプロイする"]。+ Console UIには、単一のコネクタからのデータが表示されます。複数のConsoleエージェントからのデータの表示に関するヒントについては、link:https://docs.netapp.com/us-en/console-setup-admin/task-manage-multiple-connectors.html#switch-between-connectors["複数のコンソールエージェントを操作する"^]を参照してください。

{アスタリスク}{アスタリスク} マッピング スキャン中にファイルから次のメタデータが抽出されます。

* ファイル発見時刻
* ファイルの最終アクセス日時
* ファイルの最終更新日時
* ファイル タイプ
* ファイル サイズ
* ファイル作成
* ファイル数
* 権限の抽出
* ストレージリポジトリ
* システム
* システムタイプ
* 使用済み容量


.ガバナンス ダッシュボードの違い:
[%collapsible]
====
[cols="40,25,25"]
|===
| 特徴 | フルスキャン | マップのみのスキャン 


| 古いデータ | はい | はい 


| 非ビジネスデータ | はい | はい 


| 重複したファイル | はい | はい 


| 定義済みの保存済みクエリ | はい | いいえ 


| デフォルトの保存クエリ | はい | はい 


| DDAレポート | はい | はい 


| マッピングレポート | はい | はい 


| 感度レベル検出 | はい | いいえ 


| 幅広い権限を持つ機密データ | はい | いいえ 


| オープン権限 | はい | はい 


| データの時代 | はい | はい 


| データのサイズ | はい | はい 


| カテゴリ | はい | いいえ 


| ファイルの種類 | はい | はい 
|===
====
.コンプライアンス ダッシュボードの違い:
[%collapsible]
====
[cols="40,25,25"]
|===
| 特徴 | フルスキャン | マップのみのスキャン 


| 個人情報 | はい | いいえ 


| 機密個人情報 | はい | いいえ 


| プライバシーリスク評価レポート | はい | いいえ 


| HIPAAレポート | はい | いいえ 


| PCI DSSレポート | はい | いいえ 
|===
====
.調査フィルターの違い:
[%collapsible]
====
[cols="40,25,25"]
|===
| 特徴 | フルスキャン | マップのみのスキャン 


| 保存されたクエリ | はい | はい 


| システムタイプ | はい | はい 


| システム | はい | はい 


| ストレージリポジトリ | はい | はい 


| ファイル タイプ | はい | はい 


| ファイル サイズ | はい | はい 


| 作成時間 | はい | はい 


| 発見された時間 | はい | はい 


| 最終更新日 | はい | はい 


| 最終アクセス | はい | はい 


| オープン権限 | はい | はい 


| ファイルディレクトリパス | はい | はい 


| カテゴリ | はい | いいえ 


| 感度レベル | はい | いいえ 


| 識別子の数 | はい | いいえ 


| 個人データ | はい | いいえ 


| 機密性の高い個人データ | はい | いいえ 


| データ主体 | はい | いいえ 


| 重複 | はい | はい 


| 分類ステータス | はい | ステータスは常に「限られた洞察」です 


| スキャン分析イベント | はい | はい 


| ファイルハッシュ | はい | はい 


| アクセス権を持つユーザーの数 | はい | はい 


| ユーザー/グループの権限 | はい | はい 


| ファイルの所有者 | はい | はい 


| ディレクトリタイプ | はい | はい 
|===
====