---
sidebar: sidebar 
permalink: task-deploy-overview.html 
keywords: cloud compliance, data sense, get started, deploy cloud data sense, outbound internet, endpoints, cloud compliance internet, web browser connectivity, cloud compliance access, privacy, compliance, bluexp classification 
summary: ニーズを満たすNetApp Data Classificationの展開を計画します。 
---
= NetApp Data Classification の導入方法を選択してください
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Data Classificationは、さまざまな方法で導入できます。利用可能な方法を確認して、ニーズに最適な方法を選択してください。

* link:task-deploy-cloud-compliance.html["コンソールを使用してクラウドにデプロイする"] 。コンソールは、コンソール エージェントと同じクラウド プロバイダー ネットワークにデータ分類インスタンスを展開します。
* link:task-deploy-compliance-onprem.html["インターネットにアクセスできる Linux ホストにインストールする"] 。インターネットにアクセスできるネットワーク内の Linux ホスト、またはクラウド内の Linux ホストに Data Classification をインストールします。このタイプのインストールは、オンプレミスにあるデータ分類インスタンスを使用してオンプレミスのONTAPシステムをスキャンする場合に適したオプションですが、必須ではありません。
* link:task-deploy-compliance-dark-site.html["インターネットにアクセスできないオンプレミス サイトの Linux ホストにインストールする"]_プライベート モード_ とも呼ばれます。インストール スクリプトを使用するこのタイプのインストールでは、コンソール SaaS レイヤーへの接続はありません。



TIP: オンプレミスの VMware vSphere 環境では、Data Classification は簡素化されたlink:task-deploy-ova.html["OVAを使用した導入"]をサポートします。



== オンプレミスインストールスクリプト

インターネットアクセスのある Linux ホストへのインストールとインターネット接続のないオンプレミス Linux ホストへのインストールの両方で、インストールスクリプトを使用します。スクリプトはまず、システムと環境が前提条件を満たしているかどうかを確認することから始まります。前提条件が満たされていれば、インストールが開始されます。

Linuxの準備状況を確認するための専用ソフトウェアパッケージが用意されています。検証パッケージを実行するには、link:task-test-linux-system.html["LinuxホストがData Classificationをインストールする準備ができていることを確認してください。"]を参照してください。
