---
sidebar: sidebar 
permalink: task-deploy-overview.html 
keywords: cloud compliance, data sense, get started, deploy cloud data sense, outbound internet, endpoints, cloud compliance internet, web browser connectivity, cloud compliance access, privacy, compliance, bluexp classification 
summary: ニーズを満たすNetApp Data Classificationの展開を計画します。 
---
= NetApp Data Classification の導入方法
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Data Classification は、さまざまなネットワークおよび接続要件に対応するため、複数の展開方法をサポートしています。利用可能な方法を確認し、お客様の環境に最適なオプションを選択してください。

* link:task-deploy-cloud-compliance.html["コンソールを使用してクラウドにデプロイする"] 。コンソールは、コンソール エージェントと同じクラウド プロバイダー ネットワークにデータ分類インスタンスを展開します。
* link:task-deploy-compliance-onprem.html["インターネットにアクセスできる Linux ホストにインストールする"]。データ分類機能を、ネットワーク内またはクラウド上の Linux ホストにインストールしてください。このオプションは、オンプレミスに配置された Data Classification インスタンスからオンプレミスの ONTAP システムをスキャンする場合に役立つことがありますが、インスタンスをオンプレミスに配置することは必須ではありません。
* link:task-deploy-compliance-dark-site.html["インターネットにアクセスできないオンプレミス サイトの Linux ホストにインストールする"]これは_プライベートモード_と呼ばれます。インストールスクリプトを使用するこのタイプのインストールは、Console SaaS レイヤーとの接続がありません。



TIP: オンプレミスの VMware vSphere 環境では、Data Classification は簡素化されたlink:task-deploy-ova.html["OVAを使用した導入"]をサポートします。



[[on-premises-installation-script]]
== オンプレミスインストールスクリプト

どちらのインストール方法もインストールスクリプトを使用します。このスクリプトは、システムと環境が前提条件を満たしているかどうかを確認します。前提条件を満たしている場合、インストールが開始されます。

Linuxホストが準備完了かどうかを確認するための専用ソフトウェアパッケージも利用可能です。検証パッケージを実行するには、link:task-test-linux-system.html["LinuxホストがData Classificationをインストールする準備ができていることを確認してください。"]を参照してください。
