= バージョン1.47
:allow-uri-read: 




=== バージョン1.47

.BlueXP classificationはNetAppデータ分類になりました
BlueXP classificationがNetApp Data Classification に変更されました。名前の変更に加えて、ユーザー インターフェイスも強化されました。

.BlueXPはNetAppコンソールになりました
BlueXP は、データ インフラストラクチャの管理における役割をより適切に反映するために、名前が変更され、再設計されました。

NetAppコンソールは、オンプレミスとクラウド環境全体にわたるエンタープライズ グレードのストレージとデータ サービスの集中管理を提供し、リアルタイムの分析情報、ワークフローの高速化、管理の簡素化を実現します。

変更内容の詳細については、 https://docs.netapp.com/us-en/bluexp-relnotes/index.html["NetAppコンソールのリリースノート"] 。

.アクション（プレビュー）
データ分類では、調査ページでのアクションがサポートされるようになりました。データ分類からファイルをコピー、移動、削除できます。

.ファイルのタグ付けのサポート（プレビュー）
データ分類では、個々のファイルのタグ付けがサポートされるようになりました。ファイル タグを使用すると、データを識別およびフィルター処理するために使用できる特定のファイルのカスタム識別子を作成できます。タグを使用すると、データ調査で特定の品質を識別したり、タグの結果に基づいて保存されたクエリやポリシーを作成したりできます。

詳細については、以下を参照してください。 link:https://docs.netapp.com/us-en/data-services-data-classification/task-investigate-data.html#view-file-metada["ファイルのメタデータを表示"] 。

.保存されたクエリのポリシー（プレビュー）
保存された検索の名前が保存されたクエリに変更されました。保存したクエリを実用的なポリシーに変換することもできます。保存したクエリ結果に基づいて、データを削除したり、電子メール通知を送信したりすることができます。

詳細については、以下を参照してください。 link:https://docs.netapp.com/us-en/data-services-data-classification/task-using-policies.html["ポリシーを作成"] 。
