= バージョン1.40
:allow-uri-read: 




=== バージョン1.40

このBlueXP classificationリリースには、次の更新が含まれています。

.RHEL 9.5 のサポート
このリリースでは、これまでサポートされていたバージョンに加えて、Red Hat Enterprise Linux v9.5 のサポートも提供されます。これは、ダーク サイトの展開を含む、 BlueXP classificationの手動オンプレミス インストールに適用されます。

次のオペレーティング システムでは、Podman コンテナー エンジンを使用する必要があり、 BlueXP classificationバージョン 1.30 以上が必要です: Red Hat Enterprise Linux バージョン 8.8、8.10、9.0、9.1、9.2、9.3、9.4、および 9.5。

.スキャンを優先する
構成をスキャンするときに、最も重要なスキャンを優先して、他のスキャンよりも先に実行することができます。この機能は、作業環境が多数あり、優先度の高いスキャンが最初に正常に実行されることを確認したい場合に役立ちます。

スキャンには 2 つの種類があります。

* *マッピングのみのスキャン*では、データの概要のみが提供されます。ファイルにアクセスして内部のデータを確認する必要がないため、データ ソースのマッピングを非常に迅速に実行できます。
* *マップと分類*スキャンにより、データの詳細なスキャンが可能になります。


マッピングのみのスキャンを使用してデータをすばやくスキャンし、さらに調査が必要なデータ ソースを特定し、その後、必要なデータ ソースまたはボリュームに対してのみマップと分類のスキャンを有効にすると効果的です。

優先度はマッピングのみのスキャンにのみ割り当てられ、マップと分類のスキャンには割り当てられません。

優先度はデフォルトで 1 に設定されていますが、1 ～ 10 の任意の数値に変更できます。数字が小さいほど、優先度が高くなります。優先度を設定しない場合は、スキャンに優先度 5 が割り当てられます。

優先度を変更するには、次の手順を実行します。

. BlueXP classificationメニューから、*構成*を選択します。
. 優先したいリソースを選択します。
. [アクション...] オプションから、[スキャンの優先順位付け] を選択します。


.スキャンを再試行する
このリリースでは、失敗したスキャンを再試行できます。この機能は、ネットワークの停止などの一時的な問題によりスキャンが失敗した場合に役立ちます。再設定せずにスキャンを再試行できます。

スキャンを再試行するには、次の手順を実行します。

. BlueXP classificationメニューから、*構成*を選択します。
. 次のいずれかを実行します。
+
** 失敗したスキャンをすべて再試行するには、「すべてのスキャンを再試行」を選択します。
** 特定のスキャンを再試行するには、リソースを選択し、[アクション...] オプションから [*スキャンの再試行*] を選択します。




スキャンは元のスキャンと同じ構成で再試行されます。スキャンが再度失敗した場合は、必要な回数だけ再試行できます。
