= バージョン1.40
:allow-uri-read: 




=== バージョン1.40

このBlueXP classificationリリースには、次の更新が含まれています。

.RHEL 9.5 のサポート
このリリースでは、これまでサポートされていたバージョンに加えて、Red Hat Enterprise Linux v9.5 のサポートも提供されます。これは、ダーク サイトの展開を含む、 BlueXP classificationの手動オンプレミス インストールに適用されます。

次のオペレーティング システムでは、Podman コンテナー エンジンを使用する必要があり、 BlueXP classificationバージョン 1.30 以上が必要です: Red Hat Enterprise Linux バージョン 8.8、8.10、9.0、9.1、9.2、9.3、9.4、および 9.5。

.マッピングのみのスキャンを優先する
マッピングのみのスキャンを実行する場合、最も重要なスキャンを優先できます。この機能は、作業環境が多数あり、優先度の高いスキャンが最初に完了するようにしたい場合に役立ちます。

デフォルトでは、スキャンは開始された順序に基づいてキューに入れられます。スキャンを優先順位付けする機能を使用すると、スキャンをキューの先頭に移動できます。複数のスキャンを優先できます。優先順位は先入れ先出しの順序で指定されます。つまり、最初に優先順位を指定したスキャンがキューの先頭に移動し、2 番目に優先順位を指定したスキャンはキューの 2 番目になり、以下同様に続きます。

優先権は 1 回限り付与されます。マッピング データの自動再スキャンはデフォルトの順序で実行されます。

優先順位はlink:https://docs.netapp.com/us-en/bluexp-classification/concept-classification.html["マッピングのみのスキャン"^]; マップスキャンや分類スキャンには使用できません。

詳細については、以下を参照してください。 link:https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#prioritize-scans["スキャンを優先する"^] 。

.すべてのスキャンを再試行する
BlueXP classificationは、失敗したすべてのスキャンを一括して再試行する機能をサポートしています。

**すべて再試行** 機能を使用すると、バッチ操作でスキャンを再試行できます。ネットワークの停止などの一時的な問題により分類スキャンが失敗した場合は、スキャンを個別に再試行するのではなく、1 つのボタンですべてのスキャンを同時に再試行できます。スキャンは必要に応じて何度でも再試行できます。

すべてのスキャンを再試行するには:

. BlueXP classificationメニューから、*構成*を選択します。
. 失敗したスキャンをすべて再試行するには、「すべてのスキャンを再試行」を選択します。


.分類モデルの精度向上
機械学習モデルの精度はlink:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["定義済みカテゴリ"]11%向上しました。
